CONFIG = {
    "creator": {
        "name": "Q Light Controller Plus",
        "version": "5.2.0",
        "author": "jugau-0882gn",
    },
    "engine": {
        "input_output_map": {
            "beat_generator": {"type": "Internal", "bpm": 120},
            "universes": [
                {"id": 0, "name": "Universe 1"},
                {"id": 1, "name": "Universe 2"},
                {"id": 2, "name": "Universe 3"},
                {"id": 3, "name": "Universe 4"},
            ],
        },
        "fixtures": [
            {
                "manufacturer": "Stairville",
                "model": "LED Flood Panel 150",
                "mode": "8-channel",
                "id": 0,
                "name": "LED Flood Panel 150 [1]",
                "universe": 0,
                "address": 41,
                "channels": 8,
            },
            {
                "manufacturer": "Stairville",
                "model": "LED Flood Panel 150",
                "mode": "8-channel",
                "id": 1,
                "name": "LED Flood Panel 150 [2]",
                "universe": 0,
                "address": 57,
                "channels": 8,
            },
            {
                "manufacturer": "Stairville",
                "model": "LED Flood Panel 150",
                "mode": "8-channel",
                "id": 2,
                "name": "LED Flood Panel 150 [3]",
                "universe": 0,
                "address": 153,
                "channels": 8,
            },
            {
                "manufacturer": "Stairville",
                "model": "LED Flood Panel 150",
                "mode": "8-channel",
                "id": 3,
                "name": "LED Flood Panel 150 [4]",
                "universe": 0,
                "address": 152,
                "channels": 8,
            },
            {
                "manufacturer": "Eurolite",
                "model": "LED PARty TCL spot",
                "mode": "5 channels",
                "id": 4,
                "name": "LED PARty TCL spot [5]",
                "universe": 0,
                "address": 33,
                "channels": 5,
            },
            {
                "manufacturer": "Eurolite",
                "model": "LED PARty TCL spot",
                "mode": "5 channels",
                "id": 5,
                "name": "LED PARty TCL spot [6]",
                "universe": 0,
                "address": 49,
                "channels": 5,
            },
            {
                "manufacturer": "Eurolite",
                "model": "LED PARty TCL spot",
                "mode": "5 channels",
                "id": 6,
                "name": "LED PARty TCL spot [7]",
                "universe": 0,
                "address": 129,
                "channels": 5,
            },
            {
                "manufacturer": "Eurolite",
                "model": "LED PARty TCL spot",
                "mode": "5 channels",
                "id": 7,
                "name": "LED PARty TCL spot [8]",
                "universe": 0,
                "address": 137,
                "channels": 5,
            },
            {
                "manufacturer": "Fun-Generation",
                "model": "PicoSpot 20",
                "mode": "9 Channel",
                "id": 8,
                "name": "PicoSpot 20 [9]",
                "universe": 0,
                "address": 80,
                "channels": 9,
            },
            {
                "manufacturer": "Fun-Generation",
                "model": "PicoSpot 20",
                "mode": "9 Channel",
                "id": 9,
                "name": "PicoSpot 20 [10]",
                "universe": 0,
                "address": 176,
                "channels": 9,
            },
            {
                "manufacturer": "BoomToneDJ",
                "model": "Xtrem LED",
                "mode": "Custom control",
                "id": 10,
                "name": "Xtrem LED [11]",
                "universe": 0,
                "address": 1,
                "channels": 6,
            },
            {
                "manufacturer": "BoomToneDJ",
                "model": "Xtrem LED",
                "mode": "Custom control",
                "id": 11,
                "name": "Xtrem LED [12]",
                "universe": 0,
                "address": 8,
                "channels": 6,
            },
            {
                "manufacturer": "Varytec",
                "model": "Gigabar II",
                "mode": "5-channel",
                "id": 12,
                "name": "Gigabar II [13]",
                "universe": 0,
                "address": 201,
                "channels": 5,
            },
            {
                "manufacturer": "Varytec",
                "model": "Gigabar II",
                "mode": "5-channel",
                "id": 13,
                "name": "Gigabar II [14]",
                "universe": 0,
                "address": 225,
                "channels": 5,
            },
            {
                "manufacturer": "BoomToneDJ",
                "model": "Dynamo Scan LED",
                "mode": "Custom control",
                "id": 14,
                "name": "Dynamo Scan LED [15]",
                "universe": 0,
                "address": 300,
                "channels": 9,
            },
            {
                "manufacturer": "BoomToneDJ",
                "model": "Dynamo Scan LED",
                "mode": "Custom control",
                "id": 15,
                "name": "Dynamo Scan LED [16]",
                "universe": 0,
                "address": 309,
                "channels": 9,
            },
            {
                "manufacturer": "Cameo",
                "model": "WOOKIE 200 R",
                "mode": "9 Channel",
                "id": 16,
                "name": "Cameo WOOKIE 200 R [17]",
                "universe": 0,
                "address": 17,
                "channels": 9,
            },
            {
                "manufacturer": "Ibiza",
                "model": "LAS-30G",
                "mode": "5 Channel",
                "id": 17,
                "name": "Ibiza LAS-30G (Laser)",
                "universe": 0,
                "address": 113,
                "channels": 5,
            },
        ],
    },
    "virtual_console": {
        "frames": [
            {"caption": "Page 1", "id": 0},
            {"caption": "Page 2", "id": 1},
            {"caption": "Page 3", "id": 2},
            {"caption": "Page 4", "id": 3},
        ]
    },
}

UNIVERSES = CONFIG["engine"]["input_output_map"]["universes"]
FIXTURES = CONFIG["engine"]["fixtures"]

